# Generated by Django 3.2.2 on 2021-09-18 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teaching_activities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='THLIC_Certificate',
            fields=[
                ('certificate_id', models.CharField(default=teaching_activities.models.THLIC_Certificate.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('certificate_name', models.CharField(max_length=100)),
                ('certificate_obtained_Yes_Or_No', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('staff', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching_portofolio',
            fields=[
                ('certificate_id', models.CharField(default=teaching_activities.models.Teaching_portofolio.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('TP_name', models.CharField(max_length=100)),
                ('TP_Developed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('staff', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
