# Generated by Django 3.2.3 on 2021-06-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cst_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture_departments',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcdepartments', to='cst_data.college_schools'),
        ),
        migrations.AlterField(
            model_name='archtecture_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arc4modules', to='cst_data.architecture_departments'),
        ),
        migrations.AlterField(
            model_name='biology_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciemodules', to='cst_data.science_departments'),
        ),
        migrations.AlterField(
            model_name='chemistry_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scie1modules', to='cst_data.science_departments'),
        ),
        migrations.AlterField(
            model_name='civil_environmental_and_geomatic_engineering_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eng2modules', to='cst_data.engineering_departments'),
        ),
        migrations.AlterField(
            model_name='computer_and_software_engineering_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ictmodules', to='cst_data.ict_departments'),
        ),
        migrations.AlterField(
            model_name='computer_sceince_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ict3modules', to='cst_data.ict_departments'),
        ),
        migrations.AlterField(
            model_name='construction_and_management_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcmodules', to='cst_data.architecture_departments'),
        ),
        migrations.AlterField(
            model_name='electrical_and_electronics_engineering_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engmodules', to='cst_data.engineering_departments'),
        ),
        migrations.AlterField(
            model_name='engineering_departments',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engdepartments', to='cst_data.college_schools'),
        ),
        migrations.AlterField(
            model_name='estate_management_and_valuation_models',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arc2modules', to='cst_data.architecture_departments'),
        ),
        migrations.AlterField(
            model_name='geography_and_urban_planning_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arc3modules', to='cst_data.architecture_departments'),
        ),
        migrations.AlterField(
            model_name='geology_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minmodules', to='cst_data.mining_and_geology_departments'),
        ),
        migrations.AlterField(
            model_name='ict_departments',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ictdepartments', to='cst_data.college_schools'),
        ),
        migrations.AlterField(
            model_name='information_systems_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ict2modules', to='cst_data.ict_departments'),
        ),
        migrations.AlterField(
            model_name='information_technology_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ict1modules', to='cst_data.ict_departments'),
        ),
        migrations.AlterField(
            model_name='mathematics_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scie2modules', to='cst_data.science_departments'),
        ),
        migrations.AlterField(
            model_name='mee_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eng1modules', to='cst_data.engineering_departments'),
        ),
        migrations.AlterField(
            model_name='mining_and_geology_departments',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindepartments', to='cst_data.college_schools'),
        ),
        migrations.AlterField(
            model_name='mining_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='min1modules', to='cst_data.mining_and_geology_departments'),
        ),
        migrations.AlterField(
            model_name='physics_modules',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scie3modules', to='cst_data.science_departments'),
        ),
        migrations.AlterField(
            model_name='science_departments',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciedepartments', to='cst_data.college_schools'),
        ),
    ]
